services:
  - type: web
    name: agentline-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn cloud.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: COMPANY
        value: "deploymate"
      - key: GEMINI_LIVE_VOICE
        value: "Aoede"
      - key: AGENT_NAME
        value: "Kavya"
      - key: GEMINI_API_KEY
        sync: false
      - key: GCP_SERVICE_ACCOUNT_JSON
        sync: false
      - key: PLIVO_AUTH_ID
        sync: false
      - key: PLIVO_AUTH_TOKEN
        sync: false
      - key: PLIVO_PHONE_NUMBER
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DEPLOYMATE_SMTP_USER
        sync: false
      - key: DEPLOYMATE_SMTP_PASSWORD
        sync: false
      - key: DEPLOYMATE_MONGO_URI
        sync: false
