services:
  - type: web
    name: agentline-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn cloud.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: COMPANY
        value: "nukkad"
      - key: GEMINI_LIVE_VOICE
        value: "Aoede"
      - key: AGENT_NAME
        value: "Kavya"
      - key: GEMINI_API_KEY
        sync: false
      - key: GCP_SERVICE_ACCOUNT_JSON
        sync: false
      - key: EXOTEL_API_KEY
        sync: false
      - key: EXOTEL_API_TOKEN
        sync: false
      - key: EXOTEL_ACCOUNT_SID
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false

